Repository janeljs/todo-list, pull requests merged in 2021-04, with the labels that each got.

#10 feat: jwt 토큰 인증 방식 구현
  backend/todo-list/build.gradle
  backend/todo-list/src/main/java/com/example/todolist/JwtUtil.java
  backend/todo-list/src/main/java/com/example/todolist/controller/UserController.java
  backend/todo-list/src/main/java/com/example/todolist/domain/User.java
  backend/todo-list/src/main/java/com/example/todolist/service/UserService.java
  backend/todo-list/src/main/resources/schema.sql
Labels: BE, Pair Programming, enhancement

#13 fix: jwt 인증 관련 에러 해결, 세션 인증 방식을 토큰 인증으로 변경
  .idea/workspace.xml
  backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
  backend/todo-list/src/main/java/com/example/todolist/JwtUtil.java
  backend/todo-list/src/main/java/com/example/todolist/WebConfig.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/UserController.java
  backend/todo-list/src/main/java/com/example/todolist/domain/User.java
  backend/todo-list/src/main/java/com/example/todolist/repository/CardRepository.java
  backend/todo-list/src/main/java/com/example/todolist/repository/UserRepository.java
  backend/todo-list/src/main/java/com/example/todolist/service/UserService.java
  backend/todo-list/src/main/resources/application.properties
  backend/todo-list/src/main/resources/data.sql
Labels: BE, Pair Programming

#14 feat: ApiResponse 추가
  .idea/workspace.xml
  backend/todo-list/src/main/java/com/example/todolist/ApiResponse.java
  backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
  backend/todo-list/src/main/java/com/example/todolist/Response.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
Labels: BE, Pair Programming, enhancement

#20 feat: CategoryDto, CardDto 추가
  .idea/workspace.xml
  backend/todo-list/src/main/java/com/example/todolist/ApiResponse.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CategoryController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/UserController.java
  backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
  backend/todo-list/src/main/java/com/example/todolist/domain/History.java
  backend/todo-list/src/main/java/com/example/todolist/domain/User.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardLogDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CategoryDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/HistoryDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/HistoryListDto.java
  backend/todo-list/src/main/java/com/example/todolist/repository/CardRepository.java
  backend/todo-list/src/main/java/com/example/todolist/repository/HistoryRepository.java
  backend/todo-list/src/main/java/com/example/todolist/service/CardService.java
  backend/todo-list/src/main/java/com/example/todolist/service/HistoryService.java
  backend/todo-list/src/main/java/com/example/todolist/service/UserService.java
  backend/todo-list/src/main/resources/schema.sql
  backend/todo-list/src/test/java/com/example/todolist/TodoListApplicationTests.java
Labels: BE, Pair Programming, enhancement

#25 feat: JWT를 생성할 때 user 정보 추가
  .idea/workspace.xml
  backend/todo-list/build.gradle
  backend/todo-list/src/main/java/com/example/todolist/JwtAuthInterceptor.java
  backend/todo-list/src/main/java/com/example/todolist/JwtUtil.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CategoryController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/UserController.java
  backend/todo-list/src/main/java/com/example/todolist/domain/Card.java
  backend/todo-list/src/main/java/com/example/todolist/domain/History.java
  backend/todo-list/src/main/java/com/example/todolist/domain/User.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CardLogDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/CategoryDto.java
  backend/todo-list/src/main/java/com/example/todolist/dto/HistoryDto.java
  backend/todo-list/src/main/java/com/example/todolist/repository/UserRepository.java
  backend/todo-list/src/main/java/com/example/todolist/service/CardService.java
  backend/todo-list/src/main/java/com/example/todolist/service/HistoryService.java
  backend/todo-list/src/main/java/com/example/todolist/service/UserService.java
  backend/todo-list/src/main/resources/data.sql
  backend/todo-list/src/main/resources/schema.sql
Labels: BE, Pair Programming, enhancement

#27 refactor: API Json 리스폰스 변경
  .idea/workspace.xml
  backend/todo-list/src/main/java/com/example/todolist/ApiResponse.java
  backend/todo-list/src/main/java/com/example/todolist/WebConfig.java
  backend/todo-list/src/main/java/com/example/todolist/controller/HomeController.java
  backend/todo-list/src/main/java/com/example/todolist/controller/UserController.java
  backend/todo-list/src/main/java/com/example/todolist/dto/HistoryListDto.java
  backend/todo-list/src/main/resources/data.sql
Labels: BE, Pair Programming

#34 feat: 사용자에 상관없이 카드를 이동할 수 있도록 수정
  .idea/workspace.xml
  backend/todo-list/src/main/java/com/example/todolist/WebConfig.java
  backend/todo-list/src/main/java/com/example/todolist/controller/CardController.java
  backend/todo-list/src/main/java/com/example/todolist/exception/GlobalExceptionHandler.java
  backend/todo-list/src/main/java/com/example/todolist/exception/IllegalUserAccessException.java
  backend/todo-list/src/main/java/com/example/todolist/service/CardService.java
  backend/todo-list/src/main/java/com/example/todolist/service/HistoryService.java
Labels: BE, Pair Programming

#35 [iOS] Final PR
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/gimjigyeong.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/gimjigyeong.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List/Controller/TodoDataSource.swift
  Todo_List/Todo_List/Controller/TodoDelegate.swift
  Todo_List/Todo_List/Controller/TodoTableViewController.swift
  Todo_List/Todo_List/Controller/TodoTableViewDragDelegate.swift
  Todo_List/Todo_List/Controller/TodoTableViewDropDelegate.swift
  Todo_List/Todo_List/Controller/ViewController.swift
  Todo_List/Todo_List/Extension/NotificationName.swift
  Todo_List/Todo_List/ModalView/ModalViewController.swift
  Todo_List/Todo_List/ModalView/ModalViewController.xib
  Todo_List/Todo_List/Model/TodoCard.swift
  Todo_List/Todo_List/Network/Coder.swift
  Todo_List/Todo_List/Network/Enum.swift
  Todo_List/Todo_List/Network/NetworkManager.swift
  Todo_List/Todo_List/View/TodoCell.swift
  Todo_List/Todo_List/View/TodoCell.xib
Labels: iOS

#36 [iOS] Final PR - Network 통신 구현
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/gimjigyeong.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/gimjigyeong.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List/Controller/TodoDataSource.swift
  Todo_List/Todo_List/Controller/TodoDelegate.swift
  Todo_List/Todo_List/Controller/TodoTableViewController.swift
  Todo_List/Todo_List/Controller/TodoTableViewDragDelegate.swift
  Todo_List/Todo_List/Controller/TodoTableViewDropDelegate.swift
  Todo_List/Todo_List/Controller/ViewController.swift
  Todo_List/Todo_List/Extension/NotificationName.swift
  Todo_List/Todo_List/ModalView/ModalViewController.swift
  Todo_List/Todo_List/ModalView/ModalViewController.xib
  Todo_List/Todo_List/Model/TodoCard.swift
  Todo_List/Todo_List/Network/Coder.swift
  Todo_List/Todo_List/Network/Enum.swift
  Todo_List/Todo_List/Network/NetworkManager.swift
  Todo_List/Todo_List/View/TodoCell.swift
  Todo_List/Todo_List/View/TodoCell.xib
Labels: iOS
